spring:
  datasource:
    url: jdbc:postgresql://db:5432/portfolio_db
    username: ${DB_USERNAME:portfolio_user}
    password: ${DB_PASSWORD:portfolio_pass}

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    com.kossentini.portfolio: INFO
