apiVersion: v1
kind: Service
metadata:
  name: portfolio-api
  namespace: portfolio-app
spec:
  type: NodePort
  selector:
    app: portfolio-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
